"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys

mainscript = 'run.py'

if sys.platform == 'darwin':
	
	OPTIONS = {
		'argv_emulation': True,
		'optimize': 2,
		'compressed': True,
		'includes': ['pyglet.media.drivers.openal'],
		'frameworks': [],
		'resources': ['data'],
		'semi_standalone': True
	}
	extra_args = {
		'setup_requires': ['py2app'],
		'app': [mainscript],
		'options': {'py2app': OPTIONS}
	}

elif sys.platform == 'win32':
	
	import py2exe
	
	OPTIONS = {
		'bundle_files': 1,
		'optimize': 2,
		'compressed': 1,
		'includes': ['pyglet.media.drivers.directsound'],
	}
	extra_args = {
		'setup_requires': ['py2exe'],
		'windows': [{'script': mainscript, 'dest_base': r'Ashima IV'}],
		'options': {'py2exe': OPTIONS}
	}

else:
	
	extra_args = {
		scripts: [mainscript]
	}

setup(
    name='Ashima IV',
    **extra_args
)
